export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGIN_PROGRESS = "LOGIN_PROGRESS";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILED = "LOGOUT_FAILED";
export const LOGOUT_PROGRESS = "LOGOUT_PROGRESS";

export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILED = "SIGNUP_FAILED";
export const SIGNUP_PROGRESS = "SIGNUP_PROGRESS";

export const FETCH_CARDS_SUCCESS = "FETCH_CARDS_SUCCESS";
export const FETCH_CARDS_FAILED = "FETCH_CARDS_FAILED";
export const FETCH_CARDS_PROGRESS = "FETCH_CARDS_PROGRESS";

export const ADD_CARD_SUCCESS = "ADD_CARD_SUCCESS";
export const ADD_CARD_FAILED = "ADD_CARD_FAILED";
export const ADD_CARD_PROGRESS = "ADD_CARD_PROGRESS";

export const GET_STATEMENT_SUCCESS = "GET_STATEMENT_SUCCESS";
export const GET_STATEMENT_FAILED = "GET_STATEMENT_FAILED";
export const GET_STATEMENT_PROGRESS = "GET_STATEMENT_PROGRESS";

export const PAY_BILL_SUCCESS = "PAY_BILL_SUCCESS";
export const PAY_BILL_FAILED = "PAY_BILL_FAILED";
export const PAY_BILL_PROGRESS = "PAY_BILL_PROGRESS";